// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgObFFXV3rlavsfF6suzIS9WD9mbAkKx4',
    appId: '1:492720233191:web:80569ee00edd8c4864e042',
    messagingSenderId: '492720233191',
    projectId: 'mindset-6c43a',
    authDomain: 'mindset-6c43a.firebaseapp.com',
    storageBucket: 'mindset-6c43a.appspot.com',
    measurementId: 'G-MZFYCBDP84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnArhhLpuJcbup1Ypi7diO6q49Q1gNHM',
    appId: '1:492720233191:android:5d2ead6eb7e3738564e042',
    messagingSenderId: '492720233191',
    projectId: 'mindset-6c43a',
    storageBucket: 'mindset-6c43a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAbfKENOSg9fOrbGEarL1HvbpmwBs6vA',
    appId: '1:492720233191:ios:cf08b2021eb707f364e042',
    messagingSenderId: '492720233191',
    projectId: 'mindset-6c43a',
    storageBucket: 'mindset-6c43a.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAbfKENOSg9fOrbGEarL1HvbpmwBs6vA',
    appId: '1:492720233191:ios:cf08b2021eb707f364e042',
    messagingSenderId: '492720233191',
    projectId: 'mindset-6c43a',
    storageBucket: 'mindset-6c43a.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgObFFXV3rlavsfF6suzIS9WD9mbAkKx4',
    appId: '1:492720233191:web:3f646c1648972e3e64e042',
    messagingSenderId: '492720233191',
    projectId: 'mindset-6c43a',
    authDomain: 'mindset-6c43a.firebaseapp.com',
    storageBucket: 'mindset-6c43a.appspot.com',
    measurementId: 'G-H0G7B1K1DK',
  );
}
